// GENERATED by tools/gen-default-stub.py. Do not edit by hand.
#pragma once

#include <AudioServer/AudioServerEndpoint.h>

namespace LibSerenityAudio {

// Harmless defaults for every AudioServerEndpoint::Stub method.
class AudioServerDefaultStub : public AudioServerEndpoint::Stub {
public:
    virtual ~AudioServerDefaultStub() = default;

    virtual void set_self_muted([[maybe_unused]] bool muted) override { }
    virtual Messages::AudioServer::IsSelfMutedResponse is_self_muted() override { return Messages::AudioServer::IsSelfMutedResponse(nullptr); }
    virtual Messages::AudioServer::GetSelfVolumeResponse get_self_volume() override { return Messages::AudioServer::GetSelfVolumeResponse(nullptr); }
    virtual void set_self_volume([[maybe_unused]] double volume) override { }
    virtual void set_self_sample_rate([[maybe_unused]] u32 sample_rate) override { }
    virtual Messages::AudioServer::GetSelfSampleRateResponse get_self_sample_rate() override { return Messages::AudioServer::GetSelfSampleRateResponse(nullptr); }
    virtual void set_buffer([[maybe_unused]] Audio::AudioQueue const& buffer) override { }
    virtual void clear_buffer() override { }
    virtual void start_playback() override { }
    virtual void pause_playback() override { }
};

} // namespace LibSerenityAudio
