#!/usr/bin/env python3
"""Generate a concrete default implementation of a SerenityOS IPC endpoint Stub.

The IPC compiler emits `<Name>Stub` with all-pure-virtual methods. LibWM only
implements the subset an application uses; this generator produces a base class
that satisfies the rest with harmless defaults, so LibWM can override just what
it cares about.

Non-void methods return `ResponseType(nullptr)` (the generated "invalid" token
constructor). Those defaults are never used for methods LibWM implements; if an
unimplemented synchronous method is invoked, `Stub::handle()` turns the invalid
response into an error instead of hanging.

Usage:
    gen-default-stub.py HEADER OUTPUT [--base WindowServer] [--extra-include ...]
"""
import re
import sys
from collections import Counter


def main() -> int:
    positional = []
    base = "WindowServer"
    include_dir = None
    extra_includes = []
    namespace = "LibWM"
    args = sys.argv[1:]
    i = 0
    while i < len(args):
        if args[i] == "--base":
            base = args[i + 1]
            i += 2
        elif args[i] == "--include-dir":
            include_dir = args[i + 1]
            i += 2
        elif args[i] == "--namespace":
            namespace = args[i + 1]
            i += 2
        elif args[i] == "--extra-include":
            extra_includes.append(args[i + 1])
            i += 2
        else:
            positional.append(args[i])
            i += 1

    if include_dir is None:
        include_dir = base

    if len(positional) < 2:
        print(__doc__, file=sys.stderr)
        return 2
    header, out = positional[0], positional[1]
    stub_class = f"{base}Stub"
    endpoint = f"{base}Endpoint"
    default_stub = f"{base}DefaultStub"

    text = open(header).read()
    start = text.index(f"class {stub_class} : public IPC::Stub {{")
    end = text.index("\n};", start)
    body = text[start:end]

    # Skip the concrete magic()/name()/handle() overrides by brace-matching the
    # handle() body, leaving only the pure-virtual section.
    handle_at = body.index("handle(")
    brace = body.index("{", handle_at)
    depth = 0
    i = brace
    while i < len(body):
        if body[i] == "{":
            depth += 1
        elif body[i] == "}":
            depth -= 1
            if depth == 0:
                break
        i += 1
    body = body[i + 1 :]

    pattern = re.compile(
        r"virtual\s+(.+?)\s+([A-Za-z_]\w*)\s*\((.*?)\)\s*(const)?\s*=\s*0;",
        re.DOTALL,
    )
    methods = []
    for ret, name, args, const in pattern.findall(body):
        ret = ret.strip()
        args = re.sub(r"\s+", " ", args).strip()
        if any(tok in ret for tok in (" ", "\n", "~")) or any(
            tok in args for tok in ("override", "{", "}", "return")
        ):
            continue
        methods.append((ret, name, args, bool(const)))

    if not methods:
        print(f"ERROR: no pure-virtual methods parsed from {header}", file=sys.stderr)
        return 1

    print(f"{base}: {len(methods)} methods; return types: {dict(Counter(m[0] for m in methods))}")

    lines = []
    lines.append("// GENERATED by tools/gen-default-stub.py. Do not edit by hand.")
    lines.append("#pragma once")
    lines.append("")
    for extra in extra_includes:
        lines.append(f"#include <{extra}>")
    lines.append(f"#include <{include_dir}/{endpoint}.h>")
    lines.append("")
    lines.append(f"namespace {namespace} {{")
    lines.append("")
    lines.append(f"// Harmless defaults for every {endpoint}::Stub method.")
    lines.append(f"class {default_stub} : public {endpoint}::Stub {{")
    lines.append("public:")
    lines.append(f"    virtual ~{default_stub}() = default;")
    lines.append("")
    for ret, name, args, const in methods:
        qualifier = " const" if const else ""
        if ret == "void":
            lines.append(f"    virtual void {name}({args}){qualifier} override {{ }}")
        else:
            lines.append(f"    virtual {ret} {name}({args}){qualifier} override {{ return {ret}(nullptr); }}")
    lines.append("};")
    lines.append("")
    lines.append(f"}} // namespace {namespace}")
    lines.append("")

    with open(out, "w") as f:
        f.write("\n".join(lines))
    print(f"wrote {out} ({len(methods)} methods)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
