// GENERATED by tools/gen-default-stub.py. Do not edit by hand.
#pragma once

#include <Clipboard/ClipboardServerEndpoint.h>

namespace LibWM {

// Harmless defaults for every ClipboardServerEndpoint::Stub method.
class ClipboardServerDefaultStub : public ClipboardServerEndpoint::Stub {
public:
    virtual ~ClipboardServerDefaultStub() = default;

    virtual Messages::ClipboardServer::GetClipboardDataResponse get_clipboard_data() override { return Messages::ClipboardServer::GetClipboardDataResponse(nullptr); }
    virtual void set_clipboard_data([[maybe_unused]] Core::AnonymousBuffer const& data, [[maybe_unused]] ByteString const& mime_type, [[maybe_unused]] HashMap<ByteString, ByteString> const& metadata) override { }
};

} // namespace LibWM
