// GENERATED by tools/gen-default-stub.py. Do not edit by hand.
#pragma once

#include <ConfigServer/ConfigServerEndpoint.h>

namespace LibWM {

// Harmless defaults for every ConfigServerEndpoint::Stub method.
class ConfigServerDefaultStub : public ConfigServerEndpoint::Stub {
public:
    virtual ~ConfigServerDefaultStub() = default;

    virtual void enable_permissive_mode() override { }
    virtual void pledge_domains([[maybe_unused]] Vector<ByteString> const& domains) override { }
    virtual void monitor_domain([[maybe_unused]] ByteString const& domain) override { }
    virtual Messages::ConfigServer::ListConfigGroupsResponse list_config_groups([[maybe_unused]] ByteString const& domain) override { return Messages::ConfigServer::ListConfigGroupsResponse(nullptr); }
    virtual Messages::ConfigServer::ListConfigKeysResponse list_config_keys([[maybe_unused]] ByteString const& domain, [[maybe_unused]] ByteString const& group) override { return Messages::ConfigServer::ListConfigKeysResponse(nullptr); }
    virtual Messages::ConfigServer::ReadStringValueResponse read_string_value([[maybe_unused]] ByteString const& domain, [[maybe_unused]] ByteString const& group, [[maybe_unused]] ByteString const& key) override { return Messages::ConfigServer::ReadStringValueResponse(nullptr); }
    virtual Messages::ConfigServer::ReadI32ValueResponse read_i32_value([[maybe_unused]] ByteString const& domain, [[maybe_unused]] ByteString const& group, [[maybe_unused]] ByteString const& key) override { return Messages::ConfigServer::ReadI32ValueResponse(nullptr); }
    virtual Messages::ConfigServer::ReadU32ValueResponse read_u32_value([[maybe_unused]] ByteString const& domain, [[maybe_unused]] ByteString const& group, [[maybe_unused]] ByteString const& key) override { return Messages::ConfigServer::ReadU32ValueResponse(nullptr); }
    virtual Messages::ConfigServer::ReadBoolValueResponse read_bool_value([[maybe_unused]] ByteString const& domain, [[maybe_unused]] ByteString const& group, [[maybe_unused]] ByteString const& key) override { return Messages::ConfigServer::ReadBoolValueResponse(nullptr); }
    virtual void write_string_value([[maybe_unused]] ByteString const& domain, [[maybe_unused]] ByteString const& group, [[maybe_unused]] ByteString const& key, [[maybe_unused]] ByteString const& value) override { }
    virtual void write_i32_value([[maybe_unused]] ByteString const& domain, [[maybe_unused]] ByteString const& group, [[maybe_unused]] ByteString const& key, [[maybe_unused]] i32 value) override { }
    virtual void write_u32_value([[maybe_unused]] ByteString const& domain, [[maybe_unused]] ByteString const& group, [[maybe_unused]] ByteString const& key, [[maybe_unused]] u32 value) override { }
    virtual void write_bool_value([[maybe_unused]] ByteString const& domain, [[maybe_unused]] ByteString const& group, [[maybe_unused]] ByteString const& key, [[maybe_unused]] bool value) override { }
    virtual void remove_key_entry([[maybe_unused]] ByteString const& domain, [[maybe_unused]] ByteString const& group, [[maybe_unused]] ByteString const& key) override { }
    virtual void remove_group_entry([[maybe_unused]] ByteString const& domain, [[maybe_unused]] ByteString const& group) override { }
    virtual void add_group_entry([[maybe_unused]] ByteString const& domain, [[maybe_unused]] ByteString const& group) override { }
};

} // namespace LibWM
