// GENERATED by tools/gen-default-stub.py. Do not edit by hand.
#pragma once

#include <FileSystemAccessServer/FileSystemAccessServerEndpoint.h>

namespace LibWM {

// Harmless defaults for every FileSystemAccessServerEndpoint::Stub method.
class FileSystemAccessServerDefaultStub : public FileSystemAccessServerEndpoint::Stub {
public:
    virtual ~FileSystemAccessServerDefaultStub() = default;

    virtual void request_file_read_only_approved([[maybe_unused]] i32 request_id, [[maybe_unused]] ByteString const& path) override { }
    virtual void request_file([[maybe_unused]] i32 request_id, [[maybe_unused]] i32 window_server_client_id, [[maybe_unused]] i32 window_id, [[maybe_unused]] ByteString const& path, [[maybe_unused]] Core::File::OpenMode requested_access) override { }
    virtual void prompt_open_file([[maybe_unused]] i32 request_id, [[maybe_unused]] i32 window_server_client_id, [[maybe_unused]] i32 window_id, [[maybe_unused]] ByteString const& window_title, [[maybe_unused]] ByteString const& path_to_view, [[maybe_unused]] Core::File::OpenMode requested_access, [[maybe_unused]] Optional<Vector<GUI::FileTypeFilter>> const& allowed_file_types) override { }
    virtual void prompt_save_file([[maybe_unused]] i32 request_id, [[maybe_unused]] i32 window_server_client_id, [[maybe_unused]] i32 window_id, [[maybe_unused]] ByteString const& title, [[maybe_unused]] ByteString const& ext, [[maybe_unused]] ByteString const& path_to_view, [[maybe_unused]] Core::File::OpenMode requested_access) override { }
    virtual Messages::FileSystemAccessServer::ExposeWindowServerClientIdResponse expose_window_server_client_id() override { return Messages::FileSystemAccessServer::ExposeWindowServerClientIdResponse(nullptr); }
};

} // namespace LibWM
