// GENERATED by tools/gen-default-stub.py. Do not edit by hand.
#pragma once

#include <LaunchServer/LaunchServerEndpoint.h>

namespace LibWM {

// Harmless defaults for every LaunchServerEndpoint::Stub method.
class LaunchServerDefaultStub : public LaunchServerEndpoint::Stub {
public:
    virtual ~LaunchServerDefaultStub() = default;

    virtual Messages::LaunchServer::OpenUrlResponse open_url([[maybe_unused]] URL::URL const& url, [[maybe_unused]] ByteString const& handler_name) override { return Messages::LaunchServer::OpenUrlResponse(nullptr); }
    virtual Messages::LaunchServer::GetHandlersForUrlResponse get_handlers_for_url([[maybe_unused]] URL::URL const& url) override { return Messages::LaunchServer::GetHandlersForUrlResponse(nullptr); }
    virtual Messages::LaunchServer::GetHandlersWithDetailsForUrlResponse get_handlers_with_details_for_url([[maybe_unused]] URL::URL const& url) override { return Messages::LaunchServer::GetHandlersWithDetailsForUrlResponse(nullptr); }
    virtual void add_allowed_url([[maybe_unused]] URL::URL const& url) override { }
    virtual void add_allowed_handler_with_any_url([[maybe_unused]] ByteString const& handler_name) override { }
    virtual void add_allowed_handler_with_only_specific_urls([[maybe_unused]] ByteString const& handler_name, [[maybe_unused]] Vector<URL::URL> const& urls) override { }
    virtual void seal_allowlist() override { }
};

} // namespace LibWM
