// GENERATED by tools/gen-default-stub.py. Do not edit by hand.
#pragma once

#include <WindowServer/ScreenLayout.h>
#include <WindowServer/WindowServerEndpoint.h>

namespace LibWM {

// Harmless defaults for every WindowServerEndpoint::Stub method.
class WindowServerDefaultStub : public WindowServerEndpoint::Stub {
public:
    virtual ~WindowServerDefaultStub() = default;

    virtual void create_menu([[maybe_unused]] i32 menu_id, [[maybe_unused]] String const& name, [[maybe_unused]] i32 minimum_width) override { }
    virtual void set_menu_name([[maybe_unused]] i32 menu_id, [[maybe_unused]] String const& name) override { }
    virtual void set_menu_minimum_width([[maybe_unused]] i32 menu_id, [[maybe_unused]] i32 minimum_width) override { }
    virtual void destroy_menu([[maybe_unused]] i32 menu_id) override { }
    virtual void add_menu([[maybe_unused]] i32 window_id, [[maybe_unused]] i32 menu_id) override { }
    virtual void add_menu_item([[maybe_unused]] i32 menu_id, [[maybe_unused]] i32 identifier, [[maybe_unused]] i32 submenu_id, [[maybe_unused]] ByteString const& text, [[maybe_unused]] bool enabled, [[maybe_unused]] bool visible, [[maybe_unused]] bool checkable, [[maybe_unused]] bool checked, [[maybe_unused]] bool is_default, [[maybe_unused]] ByteString const& shortcut, [[maybe_unused]] Gfx::ShareableBitmap const& icon, [[maybe_unused]] bool exclusive) override { }
    virtual void add_menu_separator([[maybe_unused]] i32 menu_id) override { }
    virtual void update_menu_item([[maybe_unused]] i32 menu_id, [[maybe_unused]] i32 identifier, [[maybe_unused]] i32 submenu_id, [[maybe_unused]] ByteString const& text, [[maybe_unused]] bool enabled, [[maybe_unused]] bool visible, [[maybe_unused]] bool checkable, [[maybe_unused]] bool checked, [[maybe_unused]] bool is_default, [[maybe_unused]] ByteString const& shortcut, [[maybe_unused]] Gfx::ShareableBitmap const& icon) override { }
    virtual void remove_menu_item([[maybe_unused]] i32 menu_id, [[maybe_unused]] i32 identifier) override { }
    virtual void flash_menubar_menu([[maybe_unused]] i32 window_id, [[maybe_unused]] i32 menu_id) override { }
    virtual void create_window([[maybe_unused]] i32 window_id, [[maybe_unused]] i32 process_id, [[maybe_unused]] Gfx::IntRect const& rect, [[maybe_unused]] bool auto_position, [[maybe_unused]] bool has_alpha_channel, [[maybe_unused]] bool minimizable, [[maybe_unused]] bool closeable, [[maybe_unused]] bool resizable, [[maybe_unused]] bool fullscreen, [[maybe_unused]] bool frameless, [[maybe_unused]] bool forced_shadow, [[maybe_unused]] float alpha_hit_threshold, [[maybe_unused]] Gfx::IntSize base_size, [[maybe_unused]] Gfx::IntSize size_increment, [[maybe_unused]] Gfx::IntSize minimum_size, [[maybe_unused]] Optional<Gfx::IntSize> const& resize_aspect_ratio, [[maybe_unused]] i32 type, [[maybe_unused]] i32 mode, [[maybe_unused]] ByteString const& title, [[maybe_unused]] i32 parent_window_id, [[maybe_unused]] Gfx::IntRect const& launch_origin_rect) override { }
    virtual Messages::WindowServer::DestroyWindowResponse destroy_window([[maybe_unused]] i32 window_id) override { return Messages::WindowServer::DestroyWindowResponse(nullptr); }
    virtual void set_window_title([[maybe_unused]] i32 window_id, [[maybe_unused]] ByteString const& title) override { }
    virtual Messages::WindowServer::GetWindowTitleResponse get_window_title([[maybe_unused]] i32 window_id) override { return Messages::WindowServer::GetWindowTitleResponse(nullptr); }
    virtual void set_window_progress([[maybe_unused]] i32 window_id, [[maybe_unused]] Optional<i32> const& progress) override { }
    virtual void set_window_modified([[maybe_unused]] i32 window_id, [[maybe_unused]] bool modified) override { }
    virtual Messages::WindowServer::IsWindowModifiedResponse is_window_modified([[maybe_unused]] i32 window_id) override { return Messages::WindowServer::IsWindowModifiedResponse(nullptr); }
    virtual Messages::WindowServer::SetWindowRectResponse set_window_rect([[maybe_unused]] i32 window_id, [[maybe_unused]] Gfx::IntRect const& rect) override { return Messages::WindowServer::SetWindowRectResponse(nullptr); }
    virtual Messages::WindowServer::GetWindowRectResponse get_window_rect([[maybe_unused]] i32 window_id) override { return Messages::WindowServer::GetWindowRectResponse(nullptr); }
    virtual Messages::WindowServer::GetWindowFloatingRectResponse get_window_floating_rect([[maybe_unused]] i32 window_id) override { return Messages::WindowServer::GetWindowFloatingRectResponse(nullptr); }
    virtual void set_window_minimum_size([[maybe_unused]] i32 window_id, [[maybe_unused]] Gfx::IntSize size) override { }
    virtual Messages::WindowServer::GetWindowMinimumSizeResponse get_window_minimum_size([[maybe_unused]] i32 window_id) override { return Messages::WindowServer::GetWindowMinimumSizeResponse(nullptr); }
    virtual Messages::WindowServer::GetAppletRectOnScreenResponse get_applet_rect_on_screen([[maybe_unused]] i32 window_id) override { return Messages::WindowServer::GetAppletRectOnScreenResponse(nullptr); }
    virtual void start_window_resize([[maybe_unused]] i32 window_id, [[maybe_unused]] i32 resize_direction) override { }
    virtual Messages::WindowServer::IsMaximizedResponse is_maximized([[maybe_unused]] i32 window_id) override { return Messages::WindowServer::IsMaximizedResponse(nullptr); }
    virtual void set_maximized([[maybe_unused]] i32 window_id, [[maybe_unused]] bool maximized) override { }
    virtual Messages::WindowServer::IsMinimizedResponse is_minimized([[maybe_unused]] i32 window_id) override { return Messages::WindowServer::IsMinimizedResponse(nullptr); }
    virtual void set_minimized([[maybe_unused]] i32 window_id, [[maybe_unused]] bool minimized) override { }
    virtual void invalidate_rect([[maybe_unused]] i32 window_id, [[maybe_unused]] Vector<Gfx::IntRect> const& rects, [[maybe_unused]] bool ignore_occlusion) override { }
    virtual void did_finish_painting([[maybe_unused]] i32 window_id, [[maybe_unused]] Vector<Gfx::IntRect> const& rects) override { }
    virtual void set_global_mouse_tracking([[maybe_unused]] bool enabled) override { }
    virtual void set_window_alpha_hit_threshold([[maybe_unused]] i32 window_id, [[maybe_unused]] float threshold) override { }
    virtual void set_window_backing_store([[maybe_unused]] i32 window_id, [[maybe_unused]] i32 bpp, [[maybe_unused]] i32 pitch, [[maybe_unused]] IPC::File const& anon_file, [[maybe_unused]] i32 serial, [[maybe_unused]] bool has_alpha_channel, [[maybe_unused]] Gfx::IntSize size, [[maybe_unused]] Gfx::IntSize visible_size, [[maybe_unused]] bool flush_immediately) override { }
    virtual void set_window_has_alpha_channel([[maybe_unused]] i32 window_id, [[maybe_unused]] bool has_alpha_channel) override { }
    virtual void move_window_to_front([[maybe_unused]] i32 window_id) override { }
    virtual void set_fullscreen([[maybe_unused]] i32 window_id, [[maybe_unused]] bool fullscreen) override { }
    virtual void set_frameless([[maybe_unused]] i32 window_id, [[maybe_unused]] bool frameless) override { }
    virtual void set_forced_shadow([[maybe_unused]] i32 window_id, [[maybe_unused]] bool shadow) override { }
    virtual void popup_menu([[maybe_unused]] i32 menu_id, [[maybe_unused]] Gfx::IntPoint screen_position, [[maybe_unused]] Gfx::IntRect const& button_rect) override { }
    virtual void dismiss_menu([[maybe_unused]] i32 menu_id) override { }
    virtual Messages::WindowServer::SetWallpaperResponse set_wallpaper([[maybe_unused]] Gfx::ShareableBitmap const& wallpaper_bitmap) override { return Messages::WindowServer::SetWallpaperResponse(nullptr); }
    virtual void set_background_color([[maybe_unused]] ByteString const& background_color) override { }
    virtual void set_wallpaper_mode([[maybe_unused]] ByteString const& mode) override { }
    virtual Messages::WindowServer::SetScreenLayoutResponse set_screen_layout([[maybe_unused]] ::WindowServer::ScreenLayout const& screen_layout, [[maybe_unused]] bool save) override { return Messages::WindowServer::SetScreenLayoutResponse(nullptr); }
    virtual Messages::WindowServer::GetScreenLayoutResponse get_screen_layout() override { return Messages::WindowServer::GetScreenLayoutResponse(nullptr); }
    virtual Messages::WindowServer::SaveScreenLayoutResponse save_screen_layout() override { return Messages::WindowServer::SaveScreenLayoutResponse(nullptr); }
    virtual void show_screen_numbers([[maybe_unused]] bool show) override { }
    virtual Messages::WindowServer::ApplyWorkspaceSettingsResponse apply_workspace_settings([[maybe_unused]] u32 rows, [[maybe_unused]] u32 columns, [[maybe_unused]] bool save) override { return Messages::WindowServer::ApplyWorkspaceSettingsResponse(nullptr); }
    virtual Messages::WindowServer::GetWorkspaceSettingsResponse get_workspace_settings() override { return Messages::WindowServer::GetWorkspaceSettingsResponse(nullptr); }
    virtual void set_window_icon_bitmap([[maybe_unused]] i32 window_id, [[maybe_unused]] Gfx::ShareableBitmap const& icon) override { }
    virtual Messages::WindowServer::GetWallpaperResponse get_wallpaper() override { return Messages::WindowServer::GetWallpaperResponse(nullptr); }
    virtual void set_window_cursor([[maybe_unused]] i32 window_id, [[maybe_unused]] i32 cursor_type) override { }
    virtual void set_window_custom_cursor([[maybe_unused]] i32 window_id, [[maybe_unused]] Gfx::ShareableBitmap const& cursor) override { }
    virtual Messages::WindowServer::StartDragResponse start_drag([[maybe_unused]] ByteString const& text, [[maybe_unused]] HashMap<String, ByteBuffer> const& mime_data, [[maybe_unused]] Gfx::ShareableBitmap const& drag_bitmap) override { return Messages::WindowServer::StartDragResponse(nullptr); }
    virtual void set_accepts_drag([[maybe_unused]] bool accepts) override { }
    virtual Messages::WindowServer::SetSystemThemeResponse set_system_theme([[maybe_unused]] ByteString const& theme_path, [[maybe_unused]] ByteString const& theme_name, [[maybe_unused]] bool keep_desktop_background, [[maybe_unused]] Optional<ByteString> const& color_scheme_path) override { return Messages::WindowServer::SetSystemThemeResponse(nullptr); }
    virtual Messages::WindowServer::GetSystemThemeResponse get_system_theme() override { return Messages::WindowServer::GetSystemThemeResponse(nullptr); }
    virtual void refresh_system_theme() override { }
    virtual Messages::WindowServer::SetSystemThemeOverrideResponse set_system_theme_override([[maybe_unused]] Core::AnonymousBuffer const& buffer) override { return Messages::WindowServer::SetSystemThemeOverrideResponse(nullptr); }
    virtual Messages::WindowServer::GetSystemThemeOverrideResponse get_system_theme_override() override { return Messages::WindowServer::GetSystemThemeOverrideResponse(nullptr); }
    virtual void clear_system_theme_override() override { }
    virtual Messages::WindowServer::IsSystemThemeOverriddenResponse is_system_theme_overridden() override { return Messages::WindowServer::IsSystemThemeOverriddenResponse(nullptr); }
    virtual Messages::WindowServer::GetPreferredColorSchemeResponse get_preferred_color_scheme() override { return Messages::WindowServer::GetPreferredColorSchemeResponse(nullptr); }
    virtual void apply_cursor_theme([[maybe_unused]] ByteString const& name) override { }
    virtual Messages::WindowServer::GetCursorThemeResponse get_cursor_theme() override { return Messages::WindowServer::GetCursorThemeResponse(nullptr); }
    virtual void set_cursor_highlight_radius([[maybe_unused]] int radius) override { }
    virtual Messages::WindowServer::GetCursorHighlightRadiusResponse get_cursor_highlight_radius() override { return Messages::WindowServer::GetCursorHighlightRadiusResponse(nullptr); }
    virtual void set_cursor_highlight_color([[maybe_unused]] Gfx::Color color) override { }
    virtual Messages::WindowServer::GetCursorHighlightColorResponse get_cursor_highlight_color() override { return Messages::WindowServer::GetCursorHighlightColorResponse(nullptr); }
    virtual Messages::WindowServer::SetSystemFontsResponse set_system_fonts([[maybe_unused]] ByteString const& default_font_query, [[maybe_unused]] ByteString const& fixed_width_font_query, [[maybe_unused]] ByteString const& window_title_font_query) override { return Messages::WindowServer::SetSystemFontsResponse(nullptr); }
    virtual void set_system_effects([[maybe_unused]] Vector<bool> const& effects, [[maybe_unused]] u8 geometry, [[maybe_unused]] u8 tile_window) override { }
    virtual void set_window_base_size_and_size_increment([[maybe_unused]] i32 window_id, [[maybe_unused]] Gfx::IntSize base_size, [[maybe_unused]] Gfx::IntSize size_increment) override { }
    virtual void set_window_resize_aspect_ratio([[maybe_unused]] i32 window_id, [[maybe_unused]] Optional<Gfx::IntSize> const& resize_aspect_ratio) override { }
    virtual void enable_display_link() override { }
    virtual void disable_display_link() override { }
    virtual void set_global_cursor_position([[maybe_unused]] Gfx::IntPoint position) override { }
    virtual Messages::WindowServer::GetGlobalCursorPositionResponse get_global_cursor_position() override { return Messages::WindowServer::GetGlobalCursorPositionResponse(nullptr); }
    virtual void set_mouse_acceleration([[maybe_unused]] float factor) override { }
    virtual Messages::WindowServer::GetMouseAccelerationResponse get_mouse_acceleration() override { return Messages::WindowServer::GetMouseAccelerationResponse(nullptr); }
    virtual void set_scroll_step_size([[maybe_unused]] u32 step_size) override { }
    virtual Messages::WindowServer::GetScrollStepSizeResponse get_scroll_step_size() override { return Messages::WindowServer::GetScrollStepSizeResponse(nullptr); }
    virtual Messages::WindowServer::GetScreenBitmapResponse get_screen_bitmap([[maybe_unused]] Optional<Gfx::IntRect> const& rect, [[maybe_unused]] Optional<u32> const& screen_index) override { return Messages::WindowServer::GetScreenBitmapResponse(nullptr); }
    virtual Messages::WindowServer::GetScreenBitmapAroundCursorResponse get_screen_bitmap_around_cursor([[maybe_unused]] Gfx::IntSize size) override { return Messages::WindowServer::GetScreenBitmapAroundCursorResponse(nullptr); }
    virtual Messages::WindowServer::GetScreenBitmapAroundLocationResponse get_screen_bitmap_around_location([[maybe_unused]] Gfx::IntSize size, [[maybe_unused]] Gfx::IntPoint location) override { return Messages::WindowServer::GetScreenBitmapAroundLocationResponse(nullptr); }
    virtual Messages::WindowServer::GetColorUnderCursorResponse get_color_under_cursor() override { return Messages::WindowServer::GetColorUnderCursorResponse(nullptr); }
    virtual void pong() override { }
    virtual void set_double_click_speed([[maybe_unused]] int speed) override { }
    virtual Messages::WindowServer::GetDoubleClickSpeedResponse get_double_click_speed() override { return Messages::WindowServer::GetDoubleClickSpeedResponse(nullptr); }
    virtual void set_mouse_buttons_switched([[maybe_unused]] bool switched) override { }
    virtual Messages::WindowServer::AreMouseButtonsSwitchedResponse are_mouse_buttons_switched() override { return Messages::WindowServer::AreMouseButtonsSwitchedResponse(nullptr); }
    virtual void set_natural_scroll([[maybe_unused]] bool inverted) override { }
    virtual Messages::WindowServer::IsNaturalScrollResponse is_natural_scroll() override { return Messages::WindowServer::IsNaturalScrollResponse(nullptr); }
    virtual Messages::WindowServer::GetDesktopDisplayScaleResponse get_desktop_display_scale([[maybe_unused]] u32 screen_index) override { return Messages::WindowServer::GetDesktopDisplayScaleResponse(nullptr); }
    virtual void set_flash_flush([[maybe_unused]] bool enabled) override { }
    virtual void set_window_parent_from_client([[maybe_unused]] i32 client_id, [[maybe_unused]] i32 parent_id, [[maybe_unused]] i32 child_id) override { }
    virtual Messages::WindowServer::GetWindowRectFromClientResponse get_window_rect_from_client([[maybe_unused]] i32 client_id, [[maybe_unused]] i32 window_id) override { return Messages::WindowServer::GetWindowRectFromClientResponse(nullptr); }
    virtual void add_window_stealing_for_client([[maybe_unused]] i32 client_id, [[maybe_unused]] i32 window_id) override { }
    virtual void remove_window_stealing_for_client([[maybe_unused]] i32 client_id, [[maybe_unused]] i32 window_id) override { }
    virtual void remove_window_stealing([[maybe_unused]] i32 window_id) override { }
    virtual void set_always_on_top([[maybe_unused]] i32 window_id, [[maybe_unused]] bool always_on_top) override { }
};

} // namespace LibWM
